# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(blank=True, max_length=16)),
                ('question_text', models.CharField(blank=True, max_length=10000)),
                ('optionA', models.CharField(blank=True, max_length=500)),
                ('optionB', models.CharField(blank=True, max_length=500)),
                ('optionC', models.CharField(blank=True, max_length=500)),
                ('optionD', models.CharField(blank=True, max_length=500)),
                ('optionE', models.CharField(blank=True, max_length=500)),
                ('correctAns', models.CharField(blank=True, max_length=500)),
                ('Marks', models.IntegerField()),
                ('NegativeMarks', models.IntegerField()),
                ('PartialMarking', models.IntegerField()),
                ('MarkingSchemeExplanation', models.CharField(default=b'No specifc instruction', max_length=1000)),
                ('question_text_image', models.ImageField(null=True, upload_to=b'photos')),
                ('question_diagram', models.ImageField(null=True, upload_to=b'photos')),
                ('optionA_image', models.ImageField(null=True, upload_to=b'photos')),
                ('optionB_image', models.ImageField(null=True, upload_to=b'photos')),
                ('optionC_image', models.ImageField(null=True, upload_to=b'photos')),
                ('optionD_image', models.ImageField(null=True, upload_to=b'photos')),
                ('optionE_image', models.ImageField(null=True, upload_to=b'photos')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(blank=True, max_length=32)),
                ('standard', models.IntegerField(default=12)),
                ('batch', models.CharField(default=b'general', max_length=16)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('teacher_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='test_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test'),
        ),
    ]
