# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='optionA_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='optionB_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='optionC_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='optionD_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='optionE_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_diagram',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_text_image',
            field=models.ImageField(blank=True, default=b'no image', upload_to=b'photos'),
        ),
    ]
