# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171129_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='test_parent',
        ),
        migrations.AddField(
            model_name='mcq',
            name='subject',
            field=models.CharField(choices=[(b'MA', b'Mathematics'), (b'CH', b'Chemistry'), (b'PH', b'Physics'), (b'GE', b'General Studies')], default=b'MA', max_length=2),
        ),
        migrations.AddField(
            model_name='test',
            name='MCQs',
            field=models.ManyToManyField(null=True, to='polls.MCQ'),
        ),
    ]
