# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_mcqproxy_testproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqproxy',
            name='question_num',
            field=models.IntegerField(default=1),
        ),
    ]
